[package]
name = "wunderkammer_derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for the Wunderkammer crate"
authors = ["Maciej Główka <mg@maciejglowka.com>"]
license = "MIT"
repository = "https://github.com/maciekglowka/wunderkammer"
publish = true
keywords = ["gamedev", "ecs", "compositioni"]
categories = ["game-development", "data-structures"]

[lib]
proc-macro = true

[features]
serialize = ["dep:serde"]

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

# TODO move to workspace dep
serde = { version = "1.0", features = ["derive"], optional = true }
